### ISSUE TITLE
when I signup it comes a waring message.

### ISSUE THREAD

**Issue by ghost** [sajalagrawal/LifestyleStore#1]
when I signup it comes a waring message.

     Warning: mysqli_connect(): (HY000/1045): Access denied for user 'id2538044_sajalagrawal'@'localhost' (using password: YES) in C:\xampp\htdocs\LifestyleStore-master\LifestyleStore\connection.php on line 2

     Warning: mysqli_error() expects parameter 1 to be mysqli, bool given in C:\xampp\htdocs\LifestyleStore-master\LifestyleStore\connection.php on line 2

how can I  solve this?

**Comment by rammohan816** [comment]
In connection.php change the code to the below code and save and run again
<?php
$con=mysqli_connect("localhost","root","","store") or die(mysqli_error($con));
?>

**Comment by rammohan816** [comment]
keep id as root and password "" i.e nill
